### ISSUE TITLE
 Missing credentials

### ISSUE THREAD

**Issue by eeeeeeeeeee555** [rrainn/AWS-SageMaker-GroundTruth-To-Azure-CustomVision#1]
Hi, 
I got an error like below. How to fix it ? Thank you for creating this lib.
![image](https://user-images.githubusercontent.com/42992667/145842742-55e28541-5ec2-42d4-b1eb-f0f42b8cb5a1.png)

**Comment by fishcharlie** [comment]
@eeeeeeeeeee555 Do you have credentials set? Take a look at [this documentation page](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-methods).

If you run `aws configure` it should walk you through the steps to setup your credentials.

Alternatively, you can set `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` environment variables to define your credentials.

**Comment by eeeeeeeeeee555** [comment]
> @eeeeeeeeeee555 Do you have credentials set? Take a look at [this documentation page](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-methods).
> 
> If you run `aws configure` it should walk you through the steps to setup your credentials.
> 
> Alternatively, you can set `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` environment variables to define your credentials.

Thank you. Unfortunately, I can't access my aws so i dont have credentials for setting up. However, i have folder of images, input manifest and output manifest file. There is any way to convert and upload them to azure custom vision ?

**Comment by fishcharlie** [comment]
@eeeeeeeeeee555 Got it.

Currently that is not supported. Everything is downloaded through AWS. There is no way currently to point to local files instead.

It is something that I could possibly add. However, the manifest files point to an S3 URL. So there would be some level of logic required to map those S3 URLs to the local file path. Maybe this tool could just take the file name and search for that.

I'll keep this issue open and will try to work on adding that functionality as soon as I can!

Thanks for the feedback.

**Comment by fishcharlie** [comment]
@eeeeeeeeeee555 I just completed this work. But I'd like you to help me test (and maybe review) it before I merge it.

The PR is up at #2.

To install it you should be able to run the following command:

```bash
npm install --g rrainn/AWS-SageMaker-GroundTruth-To-Azure-CustomVision#localAccess
```

Then after you are done testing I'd recommend uninstalling by running `npm uninstall AWS-SageMaker-GroundTruth-To-Azure-CustomVision`, and reinstall the version from npm (to ensure you don't get stuck on an old version).

Please report back if you have success with it or if there are any problems. Feel free to also review the code and let me know if you have any suggestions on that front as well.

I look forward to hearing your results! 😃

**Comment by eeeeeeeeeee555** [comment]
> @eeeeeeeeeee555 I just completed this work. But I'd like you to help me test (and maybe review) it before I merge it.
> 
> The PR is up at #2.
> 
> To install it you should be able to run the following command:
> 
> ```shell
> npm install --g rrainn/AWS-SageMaker-GroundTruth-To-Azure-CustomVision#localAccess
> ```
> 
> Then after you are done testing I'd recommend uninstalling by running `npm uninstall AWS-SageMaker-GroundTruth-To-Azure-CustomVision`, and reinstall the version from npm (to ensure you don't get stuck on an old version).
> 
> Please report back if you have success with it or if there are any problems. Feel free to also review the code and let me know if you have any suggestions on that front as well.
> 
> I look forward to hearing your results! 😃

Hi,
sorry for late response. I am testing it. I will report back the results to you. Thank you :)

**Comment by fishcharlie** [comment]
@eeeeeeeeeee555 Following up on this. Did you get a chance to test the PR? 😃
